### ISSUE TITLE
Update Kubeflow to v1.2

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow#11]
Move from current v1.0 to v1.1.

**Comment by sylus** [comment]
https://github.com/orgs/kubeflow/projects/36

**Comment by sylus** [comment]
Here is the P.R.

https://github.com/StatCan/kubeflow-manifest/pull/65/files

**Comment by sylus** [comment]
#1

```
kustomize/profiles/base/kustomization.yaml

- name: gcr.io/kubeflow-images-public/kfam

  -newName: k8scc01covidacr.azurecr.io/kfam
  -newTag: latest

  +newName: gcr.io/kubeflow-images-public/kfam
  +newTag: vmaster-gf3e09203
```

#2

kustomize/profiles/base/deployment.yaml

```
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
```

#3

kustomize/profiles/base_v3/kustomization.yaml

```
  -newName: k8scc01covidacr.azurecr.io/kfam
  -newTag: latest

  +newName: gcr.io/kubeflow-images-public/kfam
  +newTag: vmaster-gf3e09203
```

#4

kustomize/profiles/base_v3/deployment_patch.yaml

```
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
```

#5

kustomize/pipelines-ui/base/deployment.yaml

```
        - name: ARGO_ARCHIVE_LOGS
          value: "true"
        - name: ARGO_ARCHIVE_ARTIFACTORY
          value: minio
        - name: ARGO_ARCHIVE_BUCKETNAME
          value: mlpipeline
        - name: ARGO_ARCHIVE_PREFIX
          value: artifacts
```

#6

kustomize/oidc-authservice/base/statefulset.yaml

```
        - image: k8scc01covidacr.azurecr.io/oidc-authservice:latest
        + image: gcr.io/arrikto/kubeflow/oidc-authservice:6ac9400

        -value: preferred_username
        +value: email

        - value: "profile email"
        - value: "profile email groups"

      imagePullSecrets:
        - name: k8scc01covidacr-registry-connection
```

#6

kustomize/oidc-authservice/base/envoy-filter.yaml

    - istio: ingressgateway-kubeflow
    + istio: ingressgateway

#7

kustomize/notebook-controller/base/deployment.yaml

```
        env:
          - name: USE_ISTIO
            value: "false"
          - name: POD_LABELS
            value: $(POD_LABELS)
          - name: ENABLE_CULLING
            value: "true"
          - name: IDLE_TIME
            value: "1440"
          - name: CULLING_CHECK_PERIOD
            value: "1"
```

#8

kustomize/minio/base/persistent-volume-claim.yaml

```
      - storage: 200Gi
      + storage: 20Gi
```

#9

kustomize/knative-install/base/config-map.yaml

```
- gateway.kubeflow.kubeflow-gateway: "istio-ingressgateway.istio-system.svc.cluster.local"
+ gateway.kubeflow.kubeflow-gateway: "istio-ingressgateway-kubeflow.istio-system.svc.cluster.local"
```

#10

Investigate the move into AWS and restore custom config

kustomize/jupyter-web-app/base/config-map.yaml -> kustomize/jupyter-web-app/overlays/aws/config-map.yaml  <-- lots of our work is here

#11

kustomize/jupyter-web-app/base/params.env

```
KUBECOST_URL=http://kubecost-cost-analyzer.kubecost.svc.cluster.local:9090
```

#12

kustomize/jupyter-web-app/base/kustomization.yaml

```
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  -newName: k8scc01covidacr.azurecr.io/jupyter-apis
  -newTag: f938db9495db669b280529482c82ff518effaec5
  +newName: gcr.io/kubeflow-images-public/jupyter-web-app
  +newTag: vmaster-gd9be4b9e
```

# 13

kustomize/jupyter-web-app/base/deployment.yaml

```
  - replicas: 3
  + replicas: 1

      - env:
        - name: ROK_SECRET_NAME
          valueFrom:
            configMapKeyRef:
              name: parameters
              key: ROK_SECRET_NAME
        - name: UI
          valueFrom:
            configMapKeyRef:
              name: parameters
              key: UI
        - name: USERID_HEADER
          value: $(userid-header)
        - name: USERID_PREFIX
          value: $(userid-prefix)
        - name: KUBECOST_URL
          valueFrom:
            configMapKeyRef:
              name: parameters
              key: KUBECOST_URL
        image: gcr.io/kubeflow-images-public/jupyter-web-app:v0.5.0
        imagePullPolicy: $(policy)

      volumes:
      - configMap:
          name: config
          name: jupyter-web-app-config
        name: config-volume
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
```

# 14

kustomize/jupyter-web-app/base/cluster-role.yaml

```
add watches back
```

# 15

kustomize/centraldashboard/base/kustomization.yaml

```
  - newName: k8scc01covidacr.azurecr.io/kubeflow/centraldashboard
  - newTag: cb2964cb4f5562b60c97f89b7ee79e4cb179216a
  + newName: gcr.io/kubeflow-images-public/centraldashboard
  + newTag: v1.1.0-g35d7484a
```

# 16

kustomize/centraldashboard/base/deployment.yaml

```
        env:
        - name: USERID_HEADER
          value: $(userid-header)
        - name: USERID_PREFIX
          value: $(userid-prefix)
        - name: PROFILES_KFAM_SERVICE_HOST
          value: profiles-kfam.kubeflow
      serviceAccountName: centraldashboard
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
```

# 17

look at bootstrap service as last time caused us issues

# 18

kustomize/argo/base/service.yaml

```
  - type: ClusterIP     
  + type: NodePort
```

# 19

kustomize/argo/base/config-map.yaml

```
        },
        archiveLogs: true
```

# 20

kustomize/argo/base/cluster-role.yaml

```
delete on pods
```
